export const UPDATE_COLLECTION_DATA = "UPDATE_TODO_DATA";
export const READ_COLLECTION_DATA = "READ_TODO_DATA";
export const SAVE_COLLECTION_DATA = "SAVE_TODO_DATA";
export const  LOADING_COLLECTION_DATA = "LOADING_COLLECTION_DATA";
export const  LOADED_COLLECTION_DATA = "LOADED_COLLECTION_DATA";